name: Automatic Installation

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test ansible environment
    runs-on: ubuntu-latest
 
    defaults:
      run:
        working-directory: .

    steps:
    - name: Copy Repo
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Install packages
      run: |
        sudo apt update -y
        python -m pip install boto3  botocore
        sudo apt install ansible -y
        ansible --version
        echo ${{ secrets.MY_SSH_SECRET_KEY }} > ~/.ssh/id_rsa
        
    - name: Run ansible playbook
      run: |
        ansible all -i inventory_aws_ec2.yml -m ping
  
